[features]
seeds = false
skip-lint = false

[programs.localnet]
rwa_raffle = "5xAQW7YPsYjHkeWfuqa55ZbeUDcLJtsRUiU4HcCLm12M"
direct_sell = "Di1ectSe11111111111111111111111111111111111"
rwa_redeem = "RwaRede3m1111111111111111111111111111111111"

[programs.devnet]
rwa_raffle = "5xAQW7YPsYjHkeWfuqa55ZbeUDcLJtsRUiU4HcCLm12M"
direct_sell = "Di1ectSe11111111111111111111111111111111111"
rwa_redeem = "RwaRede3m1111111111111111111111111111111111"

[programs.mainnet]
# rwa_raffle = "REPLACE_WITH_MAINNET_ID"
# direct_sell = "REPLACE_WITH_MAINNET_ID"
# rwa_redeem = "REPLACE_WITH_MAINNET_ID"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.31.1"
